### ISSUE TITLE
Not working in Yandex Browser.

### ISSUE THREAD

**Issue by sampath004** [d4t4x/data-selfie#10]
Hi,
I'm using Yandex browser which was built using chromium. The data Selfie extension is not working for this browser.
Yandex browser supports all chrome extensions and I regularly use many chrome extensions and all the extensions are working fine apart from this Data Selfie extension.
Please go through the attached image.
![error](https://cloud.githubusercontent.com/assets/8466988/23338305/1bfb3a74-fc2d-11e6-8de3-f3606dcf72c0.PNG)

Thanks
Sampath | Web Developer

**Comment by 01fade** [comment]
Hi, thanks for your post. I think it could also have something to do with #2 issue. Can you check?
