### ISSUE TITLE
no data collected

### ISSUE THREAD

**Issue by wheelq** [d4t4x/data-selfie#11]
"If you have, but the counter for the seconds you look at posts (see demo video) is not shown in the bottom left, then your browser/Facebook account might not be compatible with Data Selfie. We are very sorry for this!"

What is not compatible?

**Comment by 01fade** [comment]
Hi, please refer to #2.
It is not really clear what is not compatible. My Facebook works and there is currently no way for me to test/replicate those people's Facebook structure that have problems. It seems to not be related to language nor operating system.

**Comment by serenaQ** [comment]
Does anyone fixed this issue? I have the same, after many try...

**Comment by 01fade** [comment]
@serenaQ This is the same problem as the issue #2, again it is not really clear what is not compatible or why your Facebook account or your code is different from most. My Facebook and most people's accounts work and it's difficult for me to test/replicate those people's Facebook structure that have problems. It seems to not be related to language nor operating system. Please follow issue #2 for more updates, I am posting there in a bit!
