### ISSUE TITLE
"Your local database is empty.  You have to use Facebook" 

### ISSUE THREAD

**Issue by veken1199** [d4t4x/data-selfie#15]
I receive this error everytime i try to use the extension even though i can see that my local db is populated with data

**Comment by veken1199** [comment]
I use Chrome 
Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by kankernl** [comment]
I have the same problem, but I don't see any data in my IndexDB? 

Build is the same:  60.0.3112.113 (Officiële build) (64-bits)

**Comment by kdenhartog** [comment]
I encounter the same issue, I think it may have to do with chrome APIs for extensions. Likely part of the API used for the extension became deprecated in this build because that's also when my extension stopped collecting data.

**Comment by veken1199** [comment]
you can check the content of your local db throw using Chrome -> inspect -> Application -> Storage "on the side bar" -> indexedDB and there you should find the database with all table, make sure you open the inspect while on DataSelfie app page

**Comment by veken1199** [comment]
@kdenhartog do you mind if you tell what version of chrome the application successfully ran on ?

**Comment by DarioCorno** [comment]
The only table with data in it is the page table, the other tables are empty. I'm using Chrome Version 60.0.3112.101 (Official Build) (64-bit) If it matters I can't see the time counter on FB.

**Comment by kdenhartog** [comment]
@veken1199 I'm not certain which build that it was last successful on. I am also running Version 60.0.3112.113 (Official Build) (64-bit), but my last piece of data was 8/22/17 at 3:15pm. It looks pull request #14 may fix the issue.

**Comment by 01fade** [comment]
Hi! I just fixed the bug that some people have reported to me - that it stopped tracking, i.e. people didn't see the clock and the blue border on the left of posts in their newsfeed. So, I believe it doesn't have to do with Chrome nor your OS, rather the reason was something Facebook changed in their DOM/code.

Data Selfie should be on v 0.0.13 to use the new code (might take a couple of hours). Please, let me know if it still doesn't work!

**Comment by veken1199** [comment]
Hello@01fade I ll test it and let you know. Thanks for the heads up
