### ISSUE TITLE
Not collecting data again

### ISSUE THREAD

**Issue by kdenhartog** [d4t4x/data-selfie#16]
Looks like the extension has stopped collecting data again. I'm beginning to wonder if a person at Facebook is watching this repo and intentionally breaking it.

**Comment by 01fade** [comment]
haha! That would be funny! But yeah unfortunately it is a very unstable situation with this extension.
I just pushed an update (0.0.14), hopefully this fixes it again. Please do let me know, if you still have the problem after the update!

**Comment by 01fade** [comment]
Working on a fix to collect clicks (incl linkes) and typed content (when in newsfeed). There has been another interface change on fb.com.

**Comment by 01fade** [comment]
Should be fixed now with v0.0.15. Please open new issue if any problem comes up. Thaaaanks!
