### ISSUE TITLE
Please add license information.  

### ISSUE THREAD

**Issue by ghost** [d4t4x/data-selfie#17]
Please add license information, because showing the code in itself does not make Data Selfie a Free Software.

**Comment by dineshdb** [comment]
@d4t4x Please add license info for this project so that I too can contribute to this project.

**Comment by 01fade** [comment]
Added the license info now =) Sorry for the delay! I am open for people to use and modify the code however they want, and if they decide to put in the public somewhere just give the ability to others, too and refer to the project.

**Comment by dineshdb** [comment]
@01fade  Thank you. FOSS Rocks!
